spring:
  application:
    name: manito-server

  datasource:
    url: jdbc:mysql://localhost:3306/manito?serverTimezone=Asia/Seoul
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create

jwt:
  secret-key:

oauth:
  kakao:
    client-id:
    url:
      auth:
      api: